### ISSUE TITLE
Simplify the CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [Ninscha/prj-rev-bwfs-dasmoto#5]
The universal selector will apply the styling to all elements on the page, so you only need to include the font-family property once in the * selector. The font-weight property is also shared, so you can apply it like so

```css
h1, h2, .price {
  font-weight: bold;
}
```
